### ISSUE TITLE
Feature request : Showing order of answers to be sorted by decreasing number of votes

### ISSUE THREAD

**Issue by kanihal** [AnthoPakPak/FastFinder#2]
Hi, Thanks for this useful extension.

By default, StackOverflow shows the most voted answer first if no other answer has been approved by the OP of the question.
Would it be possible to provide an option in the extension to change the showing order of answers sorted by votes instead of post time that this extension seems to have implemented?

**Comment by AnthoPakPak** [comment]
Closing since you've posted the issue on the wrong repo 😃 (correct issue [here](https://github.com/AnthoPakPak/StackOverflowPowerUser/issues/1))
